import Head from "next/head";
import Image from "next/image";
import { gql } from "@apollo/client";
import { client } from "../lib/apollo";
import {
  Stack,
  HStack,
  VStack,
  Box,
  Text,
  StackDivider,
} from "@chakra-ui/react";
import { Link } from "@chakra-ui/react";

export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>WP + Next JS project with Graphql</h1>

        {posts.map(({ title, content, slug, date, uri }) => (
          <Box key={slug} mb={5}>
            <Link href={`posts/${slug}`}>
              <Text fontSize="xl" mb={2}>
                {title}{" "}
              </Text>
              <Text fontSize="sm" d="block">
                {date}
              </Text>
            </Link>

            <Text>{content}</Text>
          </Box>
        ))}
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const result = await client.query({
    query: gql`
      query getPosts {
        posts {
          nodes {
            title
            uri
            date
            slug
            content
          }
        }

        menus {
          nodes {
            id
            databaseId
            name
            menuItems {
              edges {
                node {
                  id
                  label
                  parentId
                }
              }
            }
          }
        }
      }
    `,
  });

  console.log(result);

  return {
    props: {
      posts: result.data.posts.nodes,
      menus: result.data.menus.nodes,
      // content: result.data.posts.nodes.content,
      // date: result.data.posts.nodes.date,
      // uri: result.data.posts.nodes.uri,
    },
  };
}
